### PR TITLE
added module.exports for node support

### PR DESCRIPTION
**Pull request by 1egoman**
I was trying to use your module for a node app I was working on, so with these additions it should work properly.

### CODE REVIEW

**Comment by jmhobbs** [comment]
I like the idea, however this breaks in the browser environment where <tt>module</tt> is not defined by default.

I'm not experienced in writing across node/browser environments, can you wrap things somehow so that this isn't a problem?  Create a <tt>module</tt> object by default if it doesn't exists?

**Comment by jmhobbs** [comment]
So, this article seems to say you can do that, but then you present different interfaces on browser/node.

http://caolanmcmahon.com/posts/writing_for_node_and_the_browser/

The option given there is to wrap it and use it like a module in browser.  I'd rather not make such a breaking change, so I'm fine with the methods existing in both namespaces.

**Comment by 1egoman** [comment]
I took a look at the url you provided - the code should work now fully cross platform.

**Comment by jmhobbs** [comment]
Awesome!  Thank you!

**Comment by jmhobbs** [comment]
Whoops!  Not that used to pull requests I guess :)

**Pull request merged**
